#### Plugins ####
# List of plugins
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

#### Keybind ####
## Remap prefix binding
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

## Split panes with | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

## Reload tmux file config
bind r source-file ~/.tmux.conf

## Switch panes without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

## Pane full screen without prefix
bind -n C-Space resize-pane -Z

## Enable mouse control (optional)
set -g mouse on

## Synchronous panes
bind e set-window-option synchronize-panes

## Don't rename window automatically
set-option -g allow-rename off

## Alacritty full color
set -as terminal-features ',alacritty*:RGB'

## Statusbar theme option
set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'

set -g @rose_pine_host 'on' # Enables hostname in the status bar
set -g @rose_pine_date_time '%a %d %b %H:%M' # It accepts the date UNIX command format (man date for info)
set -g @rose_pine_directory 'off' # Turn on the current folder component in the status bar
set -g @rose_pine_bar_bg_disable 'off' # Disables background color, for transparent terminal emulators

set -g @rose_pine_default_window_behavior 'off' # Forces tmux default window list behaviour
set -g @rose_pine_show_current_program 'off' # Forces tmux to show the current running program as window name
set -g @rose_pine_show_pane_directory 'off' # Forces tmux to show the current directory as window name

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

