[general]
import = [ "~/.config/alacritty/rose-pine.toml"]
live_config_reload = true

[window]
startup_mode = "Windowed"
# title = "Alacritty Terminal"
# dynamic_title = true # default value is true

[cursor]
style = "Beam"
thickness = 0.15
unfocused_hollow = false

### Smooth Cursor
## Set to false to disable completely
# smooth_motion = true
## 0.0 = cursor is not moving, 1.0 = cursor moves instantly
# smooth_motion_factor = 0.6
## 0.0 = broken, 1.0 = cursor shape is unaffected by movement
# smooth_motion_spring = 0.6
## Limits how the cursor size may change
# smooth_motion_max_stretch_x = 3.0
# smooth_motion_max_stretch_y = 1.0
## Override "block" cursor if you don't like how it looks in this fork
## I prefer "underline"
# block_replace_shape = "Beam"

[font]
size = 14
[font.normal]
family = "HexaMono"
style = "Regular"
[font.bold]
family = "HexaMono"
style = "Bold"

[mouse]
hide_when_typing = true

### Consider to use Terminal Multiplexer at start since Alacritty only support multiple tabs on MacOS
#[terminal]
#shell = {program = "/bin/zellij", args = ["-s", "KangHexa"]}

