# BEGIN_KITTY_THEME
# Catppuccin-Mocha
# include current-theme.conf
# END_KITTY_THEME

## Window settings
  map f1 set_window_title Kitty
  remember_window_size no
  initial_window_width 82c
  initial_window_height 19c

## Font
  font_family      family=HexaMono postscript_name=HexaMonoNF-Regular
  bold_font        auto
  italic_font      auto
  bold_italic_font auto
  disable_ligatures always
  font_size 13
  text_composition_strategy platform


## Tab Config
  tab_bar_min_tabs            1
  tab_bar_edge                bottom
  tab_bar_style               powerline
  tab_powerline_style         slanted
  tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

  tab_bar_edge                    bottom
  tab_bar_align                   left
  tab_bar_margin_width            0.0
  tab_bar_margin_height           0.0 0.0
  active_tab_font_style           normal
  inactive_tab_font_style         normal
  tab_bar_min_tabs                1
  tab_activity_symbol             none

## Cursor
  cursor_shape underline
  cursor_shape_unfocused unchanged
  cursor_underline_thickness 1.0
  cursor_blink_interval 0
  cursor_trail 1
  cursor_trail_start_threshold 0
  shell_integration no-cursor

## Keyboard Shortcuts
  map ctrl+page_down previous_tab
  map ctrl+page_up next_tab
  map ctrl+shift+enter new_window
  map ctrl+shift+z toggle_layout stack
  map ctrl+shift+h neighboring_window left
  map ctrl+shift+j neighboring_window up
  map ctrl+shift+k neighboring_window down
  map ctrl+shift+l neighboring_window right
